# Generated by Django 3.0.5 on 2020-05-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200505_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_sprint_length_in_weeks',
            field=models.IntegerField(default=2),
        ),
    ]
