FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code
COPY . /code/


RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false
ADD pyproject.toml poetry.lock /code/
RUN poetry install
RUN python manage.py collectstatic --noinput

RUN adduser --disabled-login myuser && \
    chown -R myuser /code
USER myuser

EXPOSE 8000
