# Generated by Django 3.0.6 on 2020-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='finished_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='started_at',
            field=models.DateField(),
        ),
    ]
