# Generated by Django 3.0.5 on 2020-05-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_sprint_number_releases'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='tasks_done',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='number_releases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
