# Generated by Django 3.0.5 on 2020-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_auto_20200506_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='number_team_members',
            field=models.IntegerField(default=1),
        ),
    ]
