# Generated by Django 3.1.7 on 2021-02-22 12:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0006_sprint_number_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dedication_percentage', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='number_team_members',
        ),
        migrations.AddField(
            model_name='sprint',
            name='members',
            field=models.ManyToManyField(to='sprints.SprintMember'),
        ),
    ]
