name: CI

on: [push]

jobs:
  backend:
    runs-on: "ubuntu-latest"

    container:
      image:  python:3.8

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Set up poetry
        run: |
          pip3 install poetry
          poetry config virtualenvs.create true
          poetry config cache-dir

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: install deps
        run: |
          poetry run pip install --upgrade pip
          poetry install

      - name: Run tests
        run: poetry run coverage run --source='.' manage.py test --parallel
        env:
          DJANGO_SETTINGS_MODULE: project.settings_test
          DATABASE_URL: postgresql://postgres:postgres@postgres:${{ job.services.postgres.ports[5432] }}/postgres?sslmode=disable
